// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Test.Models;

namespace Test.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210613103812_AddConfiguration")]
    partial class AddConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Test.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Volume")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 33m,
                            Name = "Coca-Cola",
                            Quantity = 1,
                            Volume = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 21m,
                            Name = "Fanta",
                            Quantity = 13,
                            Volume = 1m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 47m,
                            Name = "Yupi",
                            Quantity = 51,
                            Volume = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 47m,
                            Name = "KateDrink",
                            Quantity = 51,
                            Volume = 0.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
